#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Declare global variables
//arcadeOn - boolean that indicates when arcade is used
bool arcadeOn = true;
//arcadeCheck - boolean that checks if button is in proper position
bool arcadeCheck = true;
//deadBand - int that defines dead ranges for joystick
int deadband = 15;

//arcade drive - function that controls arcade drive
/*
if both joysticks within dead range, do not move

*/
void arcadeDrive(){
	if( abs( vexRT[Ch1] ) < deadband && abs ( vexRT[Ch2] ) < deadband){
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
	}else if( abs( vexRT[Ch1] ) < deadband ){
		motor[leftMotor] = vexRT[Ch2];
		motor[rightMotor] = vexRT[Ch2]*-1;
	}else if( abs( vexRT[Ch2] ) < deadband ){
		motor[leftMotor] = vexRT[Ch1];
		motor[rightMotor] = vexRT[Ch1];
	}else if( vexRT[Ch2] > deadband ){
		motor[leftMotor] = ((vexRT[Ch2]+vexRT[Ch1]))/2;
		motor[rightMotor] = ((vexRT[Ch2]-vexRT[Ch1]))/-2;
	}else if( vexRT[Ch2] < -deadband ){
		motor[leftMotor] = ((vexRT[Ch2]+vexRT[Ch1]))/2;
		motor[rightMotor] = ((vexRT[Ch2]-vexRT[Ch1]))/-2;
	}
}

	//tankDrive - function that controls tank drive
	void tankDrive(){
		if(abs(vexRT[Ch2])<deadband){
			motor[rightMotor] = 0;
			}else{
			motor[rightMotor] = vexRT[Ch2];
		}
		if(abs(vexRT[Ch3])<deadband){
			motor[leftMotor] = 0;
			}else{
			motor[leftMotor] = vexRT[Ch2];
		}
	}

	//arcade - function that toggles between arcade and tank drive on button presses
	void arcadeLatch(){
		if(vexRT[Btn5U]&&!arcadeCheck){
			arcadeOn = !arcadeOn;
			arcadeCheck = true;
		}
		if(!vexRT[Btn5U]&&arcadeCheck){
			arcadeCheck = false;
		}
		return arcadeOn;
	}

	//drive - function that controls overall driving functionality
	void drive(){
		arcadeLatch();
		if(arcadeOn){
			arcadeDrive();
			}else{
			tankDrive();
		}
	}

	//main - thing that runs first
	task main()
	{
		while(true)
		{
			drive();
		}
	}
